/**
 * Report Generator
 * 
 * Generates coverage reports, validation summaries, and ATT&CK Navigator layers.
 */

import { Database } from 'better-sqlite3';
import { writeFileSync } from 'fs';

interface ReportConfig {
  type: 'daily' | 'weekly' | 'monthly' | 'custom';
  startDate?: string;
  endDate?: string;
  includeNavigator: boolean;
  outputPath: string;
}

interface ReportData {
  period: string;
  detections_created: number;
  validations_passed: number;
  validations_failed: number;
  coverage_improvement: number;
  prs_staged: number;
  top_techniques: Array<{ technique: string; count: number }>;
  failed_techniques: Array<{ technique: string; reason: string }>;
}

export class ReportGenerator {
  private db: Database;

  constructor(databasePath: string) {
    // this.db = new Database(databasePath);
  }

  /**
   * Generate markdown report
   */
  async generateMarkdownReport(config: ReportConfig): Promise<string> {
    const data = await this.gatherReportData(config);
    
    const markdown = `# Autonomous Detection Engineering Report

## Period: ${data.period}

### Summary

- **Detections Created**: ${data.detections_created}
- **Validations Passed**: ${data.validations_passed} (${this.calcPercentage(data.validations_passed, data.validations_passed + data.validations_failed)}%)
- **Validations Failed**: ${data.validations_failed}
- **Coverage Improvement**: +${data.coverage_improvement}%
- **PRs Staged**: ${data.prs_staged}

### Top Techniques Covered

${data.top_techniques.map(t => `- **${t.technique}**: ${t.count} detections`).join('\n')}

### Failed Validations

${data.failed_techniques.length > 0 
  ? data.failed_techniques.map(t => `- **${t.technique}**: ${t.reason}`).join('\n')
  : '_No failed validations this period_'
}

### Validation Success Rate

\`\`\`
${this.generateASCIIChart(data.validations_passed, data.validations_failed)}
\`\`\`

### Coverage Evolution

${await this.generateCoverageEvolution(config)}

---

*Generated by Autonomous Detection Platform v3.0 on ${new Date().toISOString()}*
`;

    // Write to file
    writeFileSync(config.outputPath, markdown);
    console.log(`[Report Generator] Markdown report saved to ${config.outputPath}`);

    return markdown;
  }

  /**
   * Generate ATT&CK Navigator layer
   */
  async generateNavigatorLayer(config: ReportConfig): Promise<any> {
    const techniques = await this.getValidatedTechniques(config);
    
    const layer = {
      name: `Autonomous Detection Coverage - ${config.type}`,
      versions: {
        attack: '18.1',
        navigator: '5.3.1',
        layer: '4.5'
      },
      domain: 'enterprise-attack',
      description: `Detection coverage from autonomous validation ${config.startDate} to ${config.endDate}`,
      techniques: techniques.map(t => ({
        techniqueID: t.technique_id,
        score: t.validation_count,
        color: this.getColorForValidationRate(t.validation_rate),
        comment: `${t.validation_count} validated detections (${Math.round(t.validation_rate * 100)}% success rate)`,
        enabled: true,
        metadata: [
          {
            name: 'Detections',
            value: t.detection_names.join(', ')
          },
          {
            name: 'Validation Rate',
            value: `${Math.round(t.validation_rate * 100)}%`
          }
        ]
      })),
      gradient: {
        colors: ['#ff6666', '#ffff66', '#66ff66'],
        minValue: 0,
        maxValue: 10
      },
      legendItems: [
        { label: 'Validated Detection', color: '#66ff66' },
        { label: 'Partial Coverage', color: '#ffff66' },
        { label: 'Failed Validation', color: '#ff6666' }
      ]
    };

    // Write to file
    const navigatorPath = config.outputPath.replace('.md', '_navigator.json');
    writeFileSync(navigatorPath, JSON.stringify(layer, null, 2));
    console.log(`[Report Generator] Navigator layer saved to ${navigatorPath}`);

    return layer;
  }

  /**
   * Gather report data from database
   */
  private async gatherReportData(config: ReportConfig): Promise<ReportData> {
    const startDate = config.startDate || this.getStartDate(config.type);
    const endDate = config.endDate || new Date().toISOString();

    // Query detections created
    const detectionsCreated = this.db.prepare(`
      SELECT COUNT(*) as count 
      FROM jobs 
      WHERE job_type = 'detection_creation' 
      AND status = 'completed'
      AND created_at BETWEEN ? AND ?
    `).get(startDate, endDate) as { count: number };

    // Query validation results
    const validationsPassed = this.db.prepare(`
      SELECT COUNT(*) as count 
      FROM validation_results 
      WHERE status = 'passed'
      AND validation_date BETWEEN ? AND ?
    `).get(startDate, endDate) as { count: number };

    const validationsFailed = this.db.prepare(`
      SELECT COUNT(*) as count 
      FROM validation_results 
      WHERE status = 'failed'
      AND validation_date BETWEEN ? AND ?
    `).get(startDate, endDate) as { count: number };

    // Top techniques
    const topTechniques = this.db.prepare(`
      SELECT technique_id as technique, COUNT(*) as count
      FROM validation_results
      WHERE status = 'passed'
      AND validation_date BETWEEN ? AND ?
      GROUP BY technique_id
      ORDER BY count DESC
      LIMIT 10
    `).all(startDate, endDate) as Array<{ technique: string; count: number }>;

    return {
      period: `${startDate.split('T')[0]} to ${endDate.split('T')[0]}`,
      detections_created: detectionsCreated.count,
      validations_passed: validationsPassed.count,
      validations_failed: validationsFailed.count,
      coverage_improvement: 0, // Calculate from campaign_coverage table
      prs_staged: 0, // Query from jobs table
      top_techniques: topTechniques,
      failed_techniques: []
    };
  }

  /**
   * Get validated techniques for Navigator layer
   */
  private async getValidatedTechniques(config: ReportConfig): Promise<any[]> {
    const startDate = config.startDate || this.getStartDate(config.type);
    const endDate = config.endDate || new Date().toISOString();

    return this.db.prepare(`
      SELECT 
        technique_id,
        COUNT(*) as validation_count,
        SUM(CASE WHEN status = 'passed' THEN 1 ELSE 0 END) * 1.0 / COUNT(*) as validation_rate,
        GROUP_CONCAT(detection_path, ', ') as detection_names
      FROM validation_results
      WHERE validation_date BETWEEN ? AND ?
      GROUP BY technique_id
    `).all(startDate, endDate);
  }

  private getStartDate(type: string): string {
    const now = new Date();
    
    switch (type) {
      case 'daily':
        now.setDate(now.getDate() - 1);
        break;
      case 'weekly':
        now.setDate(now.getDate() - 7);
        break;
      case 'monthly':
        now.setMonth(now.getMonth() - 1);
        break;
    }

    return now.toISOString();
  }

  private calcPercentage(part: number, total: number): string {
    if (total === 0) return '0';
    return ((part / total) * 100).toFixed(1);
  }

  private generateASCIIChart(passed: number, failed: number): string {
    const total = passed + failed;
    if (total === 0) return 'No data';

    const passedWidth = Math.round((passed / total) * 40);
    const failedWidth = 40 - passedWidth;

    return `
Passed: [${'█'.repeat(passedWidth)}${' '.repeat(failedWidth)}] ${passed}
Failed: [${'█'.repeat(failedWidth)}${' '.repeat(passedWidth)}] ${failed}
    `.trim();
  }

  private getColorForValidationRate(rate: number): string {
    if (rate >= 0.9) return '#66ff66'; // Green
    if (rate >= 0.7) return '#ffff66'; // Yellow
    return '#ff6666'; // Red
  }

  private async generateCoverageEvolution(config: ReportConfig): Promise<string> {
    // Query campaign_coverage table for temporal evolution
    // Return markdown table showing coverage % over time
    return '_Coverage evolution tracking enabled_';
  }
}

// CLI entry point
if (require.main === module) {
  const dbPath = process.env.DETECTIONS_DB_PATH || './detections.db';
  const generator = new ReportGenerator(dbPath);

  const type = (process.argv[2] || 'weekly') as ReportConfig['type'];
  const outputPath = process.argv[3] || `./report_${type}_${Date.now()}.md`;

  const config: ReportConfig = {
    type,
    includeNavigator: true,
    outputPath
  };

  generator.generateMarkdownReport(config).then(() => {
    console.log('✅ Report generated');
    
    if (config.includeNavigator) {
      generator.generateNavigatorLayer(config).then(() => {
        console.log('✅ Navigator layer generated');
      });
    }
  });
}
