/**
 * Data Dumper Node
 * 
 * Exports validated attack data from Splunk for the attack_data repository.
 * Uses Splunk MCP's export_dump tool to extract logs that triggered detections.
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { v4 as uuidv4 } from 'uuid';
import { getMCPClient, splunkExportDump } from '../tools/mcp-client.js';
import { getConfig } from '../config.js';
import type { PipelineState, Detection } from '../state/types.js';

// Standard sourcetypes for attack data
const ATTACK_DATA_SOURCETYPES = [
  {
    name: 'windows-sysmon',
    sourcetype: 'XmlWinEventLog:Microsoft-Windows-Sysmon/Operational',
    source: 'XmlWinEventLog:Microsoft-Windows-Sysmon/Operational',
    index: 'win',
  },
  {
    name: 'windows-security',
    sourcetype: 'XmlWinEventLog:Security',
    source: 'XmlWinEventLog:Security',
    index: 'win',
  },
  {
    name: 'windows-powershell',
    sourcetype: 'XmlWinEventLog:Microsoft-Windows-PowerShell/Operational',
    source: 'XmlWinEventLog:Microsoft-Windows-PowerShell/Operational',
    index: 'win',
  },
];

interface DatasetExport {
  name: string;
  path: string;
  sourcetype: string;
  source: string;
  rows_exported: number;
}

/**
 * Export attack data for a validated detection
 */
async function exportAttackData(
  detection: Detection,
  outputDir: string,
  earliest: string = '-2h'
): Promise<DatasetExport[]> {
  const client = getMCPClient();
  const exports: DatasetExport[] = [];
  
  // Create output directory
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }
  
  // Export each relevant sourcetype
  for (const st of ATTACK_DATA_SOURCETYPES) {
    const outputPath = join(outputDir, `${st.name}.log`);
    
    // Build search query
    const search = `search index=${st.index} sourcetype="${st.sourcetype}" earliest=${earliest} latest=now`;
    
    console.log(`[Data Dumper] Exporting ${st.name} to ${outputPath}`);
    
    try {
      const result = await client.callTool({
        server: 'splunk-mcp',
        tool: 'export_dump',
        arguments: {
          search,
          output_path: outputPath,
          earliest,
          latest: 'now',
          output_format: 'jsonl',
        },
      });
      
      if (result.success && result.result) {
        const exportResult = result.result as any;
        exports.push({
          name: st.name,
          path: outputPath,
          sourcetype: st.sourcetype,
          source: st.source,
          rows_exported: exportResult.rows_written || 0,
        });
        console.log(`[Data Dumper] ✓ ${st.name}: ${exportResult.rows_written || 0} rows`);
      } else if (result.result && (result.result as any)._mcp_pending) {
        // MCP not wired - log the call that would be made
        console.log(`[Data Dumper] MCP call prepared for ${st.name}`);
        exports.push({
          name: st.name,
          path: outputPath,
          sourcetype: st.sourcetype,
          source: st.source,
          rows_exported: 0,
        });
      }
    } catch (error) {
      console.error(`[Data Dumper] Error exporting ${st.name}:`, error);
    }
  }
  
  return exports;
}

/**
 * Generate attack_data dataset YAML
 */
function generateDatasetYaml(
  detection: Detection,
  exports: DatasetExport[],
  techniqueDir: string
): string {
  const today = new Date().toISOString().split('T')[0];
  
  const datasets = exports
    .filter(e => e.rows_exported > 0)
    .map(e => ({
      name: e.name,
      path: `/datasets/attack_techniques/${detection.technique_id}/autonomous_agent/${e.name}.log`,
      sourcetype: e.sourcetype,
      source: e.source,
    }));
  
  const yaml = `author: Autonomous Detection Agent
id: ${uuidv4()}
date: '${today}'
description: |
  Validated attack data for detection: ${detection.name}
  Technique: ${detection.technique_id}
  Generated by autonomous detection pipeline after successful Atomic Red Team validation.
environment: attack_range
directory: autonomous_agent
mitre_technique:
- ${detection.technique_id}
datasets:
${datasets.map(d => `- name: ${d.name}
  path: ${d.path}
  sourcetype: ${d.sourcetype}
  source: ${d.source}`).join('\n')}
`;
  
  return yaml;
}

export async function dataDumperNode(state: PipelineState): Promise<Partial<PipelineState>> {
  console.log('[Data Dumper] Exporting attack data for validated detections...');
  
  const cfg = getConfig();
  
  // Dry-run mode: return mock export paths
  if (cfg.dryRun) {
    console.log('[Data Dumper] Dry-run mode - returning mock export paths');
    const mockPaths = state.detections
      .filter(d => d.status === 'validated')
      .map(d => `/mock/attack_data/${d.technique_id}/autonomous_agent/mock.log`);
    
    console.log(`[Data Dumper] Mock exported ${mockPaths.length} file(s)`);
    
    return {
      attack_data_paths: mockPaths,
      current_step: 'data_dump_complete',
      warnings: ['Dry-run mode: no actual data exported from Splunk'],
    };
  }
  
  // Only export for validated detections
  const validatedDetections = state.detections.filter(d => d.status === 'validated');
  
  if (validatedDetections.length === 0) {
    console.log('[Data Dumper] No validated detections to export');
    return { current_step: 'data_dump_complete' };
  }

  const attackDataPaths: string[] = [];

  for (const detection of validatedDetections) {
    try {
      console.log(`[Data Dumper] Processing: ${detection.name} (${detection.technique_id})`);
      
      // Create directory structure
      const techniqueDir = join(getConfig().attackDataPath, 'datasets', 'attack_techniques', detection.technique_id, 'autonomous_agent');
      
      // Export data from Splunk
      const exports = await exportAttackData(detection, techniqueDir, '-2h');
      
      // Generate dataset YAML
      const yamlContent = generateDatasetYaml(detection, exports, techniqueDir);
      const yamlPath = join(techniqueDir, `${detection.technique_id.toLowerCase().replace('.', '_')}_autonomous.yml`);
      
      writeFileSync(yamlPath, yamlContent);
      console.log(`[Data Dumper] ✓ Written dataset YAML: ${yamlPath}`);
      
      attackDataPaths.push(yamlPath);
      
      // Also track the log files
      exports.forEach(e => {
        if (e.rows_exported > 0) {
          attackDataPaths.push(e.path);
        }
      });

    } catch (error) {
      console.error(`[Data Dumper] Error processing ${detection.name}:`, error);
    }
  }

  console.log(`[Data Dumper] Exported ${attackDataPaths.length} files`);

  return {
    attack_data_paths: attackDataPaths,
    current_step: 'data_dump_complete',
  };
}
